version: "3.8"
services:
  bot:
    build: 
      context: ./bot
    image: newspaper-bot
    container_name: "newspaper-bot"
    environment:
    - TOKEN=
    - REDDIT_CLIENT_ID=
    - REDDIT_SECRET=
    - REDDIT_USER_AGENT=
  
  scraper:
    build: 
      context: ./scraper
    image: newspaper-scraper
    container_name: "newspaper-scraper"
